### ISSUE TITLE
Feature request: Display a table of which devices belong to a graph

### ISSUE THREAD

**Issue by maglub** [do3meli/piLogger-cloud-frontend#10]
I.e http://pilogger.net/graphs/1

The table should contain the following information:

* sensor id
* device id

The location of this table could either be in the graph page or in some other configuration related page.

**Comment by do3meli** [comment]
Shouldnt the question be: which sensor belongs to which graph? Because a device has just sensors attached and has no metrics...

**Comment by maglub** [comment]
A sensor is connected to a device, and I think it would be interesting to see which sensor (and device) is being displayed on a graph. For example, if I would decide to name one sensor "fnorp" on one device, and use the same name "fnorp" for another sensor on a different device, it would be very hard to figure out which sensor is displayed on a graph by just looking at the graph.

That is why I would like to see a table with the origin of the data together with the graph (or as an option).

**Comment by do3meli** [comment]
wouldn't it be much easier to adjust the legend below the graphs? 
we could use legend names like `%device%:%sensor%`

**Comment by maglub** [comment]
Perhaps, yes, as a quick fix. At some point there will be a "graph
designer", where one would pick and choose what sensors from which devices
to display on a graph.
